name: build
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  push:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: bazelisk build --disk_cache=/tmp/bazel-cache -c opt //:vrising_dedicated_image.tar

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: bazelisk run @com_github_google_go_containerregistry//cmd/crane:crane -- push --platform linux/amd64 $(bazelisk info -c opt bazel-bin)/vrising_dedicated_image.tar ghcr.io/${{ github.repository }}:${{ github.sha }}
